household_power_consumption <- read.csv(file="D:/documents/coursera/ExData_Plotting1/household_power_consumption.txt", sep=";", dec=".")
house2007<-household_power_consumption[which(household_power_consumption=="1/2/2007" | household_power_consumption=="2/2/2007"),]
rm(household_power_consumption)
#house2007$Date<-as.Date(house2007$Date, format="%d/%m/%Y")
house2007$Time<-strptime(paste(house2007$Date, house2007$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
house2007$Global_active_power<-as.numeric(as.character(house2007$Global_active_power))
house2007$Global_reactive_power<-as.numeric(as.character(house2007$Global_reactive_power))
house2007$Voltage<-as.numeric(as.character(house2007$Voltage))
house2007$Global_intensity<-as.numeric(as.character(house2007$Global_intensity))
#house2007$Sub_metering_1<-as.numeric(as.character(house2007$Sub_metering_1))
#house2007$Sub_metering_2<-as.numeric(as.character(house2007$Sub_metering_2))
#house2007$Sub_metering_3<-as.numeric(as.character(house2007$Sub_metering_3))
png(filename="plot2.png", width=480, height=480)
Sys.setlocale(locale = "C")
plot(x=house2007$Time, y=house2007$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", main="", type="l")
dev.off()